server:
  port: 8761

eureka:
  instance:
    hostname: registry
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
  client:
    #是否将自己注册到Eureka Server
    registerWithEureka: false
    #是否从Eureka Server获取注册信息
    fetchRegistry: false
    service-url:
      #设置与Eureka Server交互的地址，查询服务和注册服务都需要依赖这个地址。默认是http://localhost:8761/eureka ；多个地址可使用 , 分隔
      defaultZone: http://${security.user.name}:${security.user.password}@${eureka.instance.hostname}:${server.port}/eureka/

security:
  basic:
    enable: true #开启基于HTTP basic的认证
  user:
    name: user
    password: ${REGISTRY_SERVER_PASSWORD:password}
